"""adding scimago_rank conference ranking table

Revision ID: 4cffea26df81
Revises: 195350944546
Create Date: 2025-10-12 12:28:19.741018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cffea26df81'
down_revision: Union[str, Sequence[str], None] = '195350944546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('conference', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('conferenceranking', sa.Column('scimago_rank', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='scimagoranking'), nullable=True))
    op.add_column('revue', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revue', 'url')
    op.drop_column('conferenceranking', 'scimago_rank')
    op.drop_column('conference', 'url')
    # ### end Alembic commands ###
