"""Updates sur labo et chercheurs

Revision ID: 79c15b91e460
Revises: 9ada087af3e8
Create Date: 2025-09-23 23:38:29.708903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79c15b91e460'
down_revision: Union[str, Sequence[str], None] = '9ada087af3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("labo", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique", ["nom"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labo', type_='unique')
    # ### end Alembic commands ###
