"""Tables chercheurs et labo ajoutés

Revision ID: 9ada087af3e8
Revises: 
Create Date: 2025-09-22 22:17:45.162483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ada087af3e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('siteweb', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chercheur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grade', sa.Enum('DOCTORANT', 'MAITRE_ASSISTANT_B', 'MAITRE_ASSISTANT_A', 'MAITRE_CONFERENCE_B', 'MAITRE_CONFERENCE_A', 'PROFESSEUR', name='gradeenum'), nullable=False),
    sa.Column('google_scholar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dblp_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=False),
    sa.Column('i_10_index', sa.Integer(), nullable=False),
    sa.Column('labo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labo_id'], ['labo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chercheur')
    op.drop_table('labo')
    # ### end Alembic commands ###
