"""Adding citations column

Revision ID: fd0bcaa02148
Revises: c8888803ace1
Create Date: 2025-10-15 16:49:26.889320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd0bcaa02148'
down_revision: Union[str, Sequence[str], None] = 'c8888803ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicationrevue', sa.Column('citations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicationrevue', 'citations')
    # ### end Alembic commands ###
